### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by jajalobrit** [Retro-Devils/Mugen-Pi-4#1]
hi! When trying to run the installation the command returns error 404 ( the url https://git.io/JusKp  is offline)

**Comment by Retro-Devils** [comment]
Good day . Sorry for late response . We are updated everything on Github now . 
That scriptnis dated and a new script will be uploaded now .

**Comment by Retro-Devils** [comment]
If this issue is solved for you please let us know. So we can help you or close issue .
