### ISSUE TITLE
Older version compile/install

### ISSUE THREAD

**Issue by actraiser30** [Retro-Devils/Mugen-Pi-4#10]
Hello there,is it possible to tell me how can install the previous mugen-pi version with wine v5? As I read many games that don't work correct with wine v6 they work great with wine v5 

Thanks in advance

**Comment by Retro-Devils** [comment]
We havemt changed the install since building. All games that worked stillWork. .

**Comment by actraiser30** [comment]
Hi,all I'm saying is that the installer does not work in Raspbian
bookworm,is there a fix for this?

**Comment by Retro-Devils** [comment]
Oh I'd have to look agian but I'm pretty sure we made just for retropie. 

Thiers alternative ways to install on Raspbian or Berry OS (pi default) .

**Comment by Retro-Devils** [comment]
Not built for raspbian or bookworm
