### ISSUE TITLE
Installing mono and gecko

### ISSUE THREAD

**Issue by christophe1979** [Retro-Devils/Mugen-Pi-4#3]
I tried the script earlier and was always prompted to install mono and gecko the first time I opened winetricks. This no longer happens and I just get a black screen and mouse cursor when opening any wine apps

**Comment by Retro-Devils** [comment]
Yeah we just tested yesterday same results for us . We will be investigating .

**Comment by christophe1979** [comment]
Thank you for your response. The script is brilliant BTW!

**Comment by Retro-Devils** [comment]
So good day. 

Were you trying to install on newest retropie release?  Cause we tested on older one work fine. The new retropie os didn't not work for us ,

**Comment by christophe1979** [comment]
Hi there,

I was trying to build it on retropie built on retropie-buster-4.7.1. The script definitely worked when i first tried it and then later it no longer did.

**Comment by Retro-Devils** [comment]
Hmmm we are still looking into id try to uodate and upgrade. . Thats just fixed cuohead for someone we know

**Comment by Retro-Devils** [comment]
Hmmm we are still looking into id try to uodate and upgrade. . Thats just fixed cuohead for someone we know

**Comment by christophe1979** [comment]
I updated and upgraded and it worked.

Thank you very much for your help.

**Comment by Retro-Devils** [comment]
Awesome
