### ISSUE TITLE
Failed running Cuphead

### ISSUE THREAD

**Issue by jajalobrit** [Retro-Devils/Mugen-Pi-4#4]
Hi, I saw that Cuphead can be run but I've tried in several ways and I couldn't.
Trying with a copy of the game files or even installing the game through wine explorer (GOG version) a popup appears when I try to run the game: 
"Failed to initialize graphics.
Make sure you have DirectX 11 installed, have up to date
drivers for your graphics card and have not disabled
3D acceleration in display settings.
InitializeEngineGraphics failed"

Do I need to do any extra configuration?
My attempts made on Raspberry pi 4-4GB, after installing the script with the option "mugen with all updates", installing gecko and mono and changing windows version to windows 7 ( when it was on windows xp, a popup was displayed saying that the game is not compatible with this version).
I will be grateful if you can help me.

**Comment by Retro-Devils** [comment]
Cuphead is a pain. We suggest checking out Devils Box on github , and our Facebook group . 
Cuphead can be download thru Devils Box ;)

https://github.com/Retro-Devils/Devils-Box

**Comment by Retro-Devils** [comment]
Also just seen your github . Forked your RetropieWatch . Very nice .

**Comment by jajalobrit** [comment]
Great, i'll check out Devils Box, thank you.  Nice that you forked the watch, it needs someone to improve it.
