### ISSUE TITLE
I can't see winetricks

### ISSUE THREAD

**Issue by lfcing** [Retro-Devils/Mugen-Pi-4#6]
After I install all mugen-pi-4 kit ,I can't see winetricks.
And I checked I can't see ./wine folder, I thought I installed failed.
What should I do?

**Comment by Retro-Devils** [comment]
Interesting.  I assume you ran recently .

I am about to run the installer on a fresh os in about a hour .

**Comment by Retro-Devils** [comment]
Open and run winetricks . Then close should generate the ./wine folder

**Comment by lfcing** [comment]
Actually , I running mugen-pi-4 first time was successful first time. But after that, I could not run Emulation station so I re-installed several times.
Whith command can I  input to install winetricks?

**Comment by Retro-Devils** [comment]
I dont think thier is a command to install just wine tricks. Sometimes you unfortunately have to launch wine games multi times.

**Comment by Retro-Devils** [comment]
Issue solved ?

**Comment by lfcing** [comment]
Actually, I installed Devil-pi then I could enter tricks. But I couldn't install DX9.... When I run DX9 game, system would crash and quit.

**Comment by Retro-Devils** [comment]
damn sorry been caught one other projects. Havent forgot this one or making a tutorial . But i havent had time yet.

**Comment by actraiser30** [comment]
Hello there winetricks has an issue I think,when it opens for first time after installed mugenn-pi,it does not prompt for installation of gecko and mono,it just opens it's main menu.
Can you fix that?

**Comment by actraiser30** [comment]
Ignore my message it was my fault it works great

**Comment by Retro-Devils** [comment]
Ok
